#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

until echo 'PING' | nc -w 1 redis 6379 | grep -q PONG
do
    echo "Waiting for Redis connection..."
    sleep 5
done

php /var/www/html/artisan config:cache

if [ "$role" = "app" ]; then

    exec apache2-foreground

elif [ "$role" = "queue" ]; then

    chown www-data:www-data storage/app/downloads
    gosu www-data nice php /var/www/html/artisan queue:work --timeout=3500

elif [ "$role" = "migrations" ]; then

    gosu www-data touch /tmp/sqlite/database.sqlite
    gosu www-data php /var/www/html/artisan migrate --force
    while [ true ]
    do
        sleep 86400
    done

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
